name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest # Замените на вашу ОС

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create known_hosts file
      run: touch ~/.ssh/known_hosts
    - name: Deploy to Server
      run: |
        ssh-keyscan -t rsa {{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts # Добавить сервер в список известных хостов
        chmod 600 ~/.ssh/id_rsa # Установить правильные права доступа для ключа
        scp -i ~/.ssh/id_rsa -r /path/to/your/script.sh {{ secrets.FTP_USERNAME }}@{{ secrets.FTP_SERVER }}:{{ variables.FTP_PATH }}
        ssh -i ~/.ssh/id_rsa {{ secrets.FTP_USERNAME }}@{{ secrets.FTP_SERVER }} "{{ variables.FTP_PATH }}/deploy.sh"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

