name: Deploy to VDS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Deploy to VDS
        run: |
          # Замените секреты и адрес VDS на ваше реальное значение
          ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd ${{ vars.FTP_PATH }}&& git pull origin master && pm2 restart ekspert-realty"
          
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Install dependencies
        run: |
          cd ${{ vars.FTP_PATH }}
          npm i

      - name: Build Nuxt.js project
        run: |
          cd ${{ vars.FTP_PATH }}
          npm run build


        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
