name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest # Выберите соответствующую ОС

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Добавьте ваш ключ SSH как секрет в репозиторий

    - name: Deploy to Server
      run: |
        # Подключение к серверу и выполнение скрипта .sh
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} {{ secrets.FTP_USERNAME }}@{{ secrets.FTP_SERVER }} "cd {{ variables.FTP_PATH }} && ./update.sh"
